-- Murungaru HealthCare Management System Schema
-- Protocol: B.L.A.S.T. | Phase: 3 (Architect)
-- Generated by: System Pilot

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Patients Table
CREATE TABLE IF NOT EXISTS public.patients (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    phone TEXT UNIQUE NOT NULL,
    full_name TEXT NOT NULL,
    dob DATE NOT NULL,
    gender TEXT CHECK (gender IN ('Male', 'Female', 'Other')),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.patients ENABLE ROW LEVEL SECURITY;

-- Policies for Patients
-- Policy: Users can view/edit their own profile based on phone number match (assuming auth.uid() links to phone or metadata)
-- For simplicity in this logical phase, we assume a 'staff' role check or 'self' check. 
-- REAL IMPLEMENTATION NOTE: Requires linking auth.users.phone to patients.phone

-- 2. Staff Table (Managed via Auth, but public profile here)
CREATE TABLE IF NOT EXISTS public.staff (
    id UUID PRIMARY KEY REFERENCES auth.users(id),
    full_name TEXT NOT NULL,
    role TEXT CHECK (role IN ('Doctor', 'Nurse', 'Admin', 'Pharmacist')),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.staff ENABLE ROW LEVEL SECURITY;

-- 3. Vitals (Triage)
CREATE TABLE IF NOT EXISTS public.vitals (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    patient_id UUID REFERENCES public.patients(id) ON DELETE CASCADE,
    staff_id UUID REFERENCES public.staff(id),
    systolic INTEGER,
    diastolic INTEGER,
    heart_rate INTEGER,
    temperature DECIMAL(4,1),
    sp_o2 INTEGER,
    weight DECIMAL(5,2),
    height DECIMAL(5,2),
    recorded_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.vitals ENABLE ROW LEVEL SECURITY;

-- 4. Consultations
CREATE TABLE IF NOT EXISTS public.consultations (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    patient_id UUID REFERENCES public.patients(id) ON DELETE CASCADE,
    doctor_id UUID REFERENCES public.staff(id),
    symptoms TEXT,
    diagnosis TEXT,
    clinical_notes TEXT,
    mch_notes TEXT, -- Maternal Child Health specifics
    prescription TEXT, -- Simple text for now, could be JSON or separate table later
    status TEXT CHECK (status IN ('waiting', 'in_progress', 'completed')) DEFAULT 'waiting',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.consultations ENABLE ROW LEVEL SECURITY;

-- 5. Inventory
CREATE TABLE IF NOT EXISTS public.inventory (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    item_name TEXT NOT NULL,
    category TEXT NOT NULL, -- e.g. 'Medicine', 'Equipment'
    stock_level INTEGER DEFAULT 0,
    reorder_point INTEGER DEFAULT 10,
    unit TEXT, -- e.g. 'tablets', 'bottles'
    expiry_date DATE,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.inventory ENABLE ROW LEVEL SECURITY;

-- RLS POLICIES (Templates)

-- Patient Access Policies
CREATE POLICY "Patients can view own profile" ON public.patients
    FOR SELECT USING (auth.uid() IN (SELECT id FROM auth.users WHERE phone = patients.phone)); -- Logic to be refined with actual auth config

CREATE POLICY "Patients can view own vitals" ON public.vitals
    FOR SELECT USING (patient_id IN (SELECT id FROM public.patients WHERE phone = (SELECT phone FROM auth.users WHERE id = auth.uid())));

CREATE POLICY "Patients can view own consultations" ON public.consultations
    FOR SELECT USING (patient_id IN (SELECT id FROM public.patients WHERE phone = (SELECT phone FROM auth.users WHERE id = auth.uid())));

-- Staff Access Policies (Full Access for Demo/MVP, refine for Prod)
CREATE POLICY "Staff can view all patients" ON public.patients
    FOR ALL USING (auth.uid() IN (SELECT id FROM public.staff));

CREATE POLICY "Staff can manage vitals" ON public.vitals
    FOR ALL USING (auth.uid() IN (SELECT id FROM public.staff));

CREATE POLICY "Staff can manage consultations" ON public.consultations
    FOR ALL USING (auth.uid() IN (SELECT id FROM public.staff));

CREATE POLICY "Staff can manage inventory" ON public.inventory
    FOR ALL USING (auth.uid() IN (SELECT id FROM public.staff));
